main_app/urls.py
from django.urls import path
from . import views

urlpatterns=[
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('media/', views.media_index, name='index'),
    path('media/<int:media_id>/', views.media_detail, name='detail'),
    path('media/create/', views.MediaCreate.as_view(),name='media_create'),
    path('media/<int:pk>/update/', views.MediaUpdate.as_view(), name="media_update"),
    path('media/<int:pk>/delete/', views.MediaDelete.as_view(), name="media_delete"),
]

readinglist/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/models.py
from django.db import models

# Create your models here.
STATUS=(
    ('N','Not Started'),
    ('S','Started'),
    ('C','Completed'),
    ('A','Abandoned'),
)

RATING=(
    (1, '1'),
    (2,'2'),
    (3,'3'),
    (4,'4'),
    (5,'5')
)

TYPE = (
    ("B","Book"),
    ("P", "Podcast"),
    ("M","Movie"),
    ("A", "Article"),
    ("V", "Video"),
    ("P", "Paper")
)

class Author(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.name}"

class Media(models.Model):
    name = models.CharField(max_length=150)
    score = models.IntegerField(
        choices=RATING,
        )
    type = models.CharField(
        max_length=100,
        choices=TYPE,
        default=TYPE[0][0]
        )
    authors = models.ManyToManyField(Author)
    status = models.CharField(
        max_length=1,
        choices=STATUS,
        default=STATUS[0][0]
    )

    notes = models.TextField(max_length=1000)
    # user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name}"

main_app/views.py
from django.shortcuts import render
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .models import Media

# media =[
#     {'name': 'Elephant in the Brain', 'type': 'Book', 'author':'Kevin Simler & Robin Hanson', 'status':'finished','rating': 5, 'notes': 'great book'},
#     {'name': 'Elephant in the Brain', 'type': 'Book', 'author':'Kevin Simler & Robin Hanson', 'status':'finished','rating': 5, 'notes': 'great book'},
#     {'name': 'Elephant in the Brain', 'type': 'Book', 'author':'Kevin Simler & Robin Hanson', 'status':'finished','rating': 5, 'notes': 'great book'},
#     {'name': 'Elephant in the Brain', 'type': 'Book', 'author':'Kevin Simler & Robin Hanson', 'status':'finished','rating': 5, 'notes': 'great book'},
# ]

# Create your views here.

def home(request):
    return render(request,'home.html')

def about(request):
    return render(request, 'home.html')

def media_index(request):
    media= Media.objects.all()
    return render(request,'media/index.html',{
        'media': media
    })

def media_detail(request, media_id):
    media = Media.objects.get(id=media_id)

    return render(request, 'media/detail.html',{
        'media': media
    })

class MediaCreate(CreateView):
    model = Media
    fields = '__all__'
    def form_valid(self, form):
        form.instance.user=self.request.user
        return super().form_valid(form)


class MediaUpdate(UpdateView):
    model = Media
    fields = '__all__'

class MediaDelete(DeleteView):
    model = Media
    succes_url = '/cats'

main_app/templates/about.html
{% extends 'base.html' %}
{%block content%}
<h1>About Page</h1>
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Modern Reading List</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;Modern Reading List</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url 'about'%}">About</a></li>
          <li><a href="{% url 'index' %}">My List</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2023 Modern Reading List&nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/home.html
{% extends 'base.html' %}
{%block content%}
<h1>Home Page</h1>

{% endblock %}

main_app/templates/media/detail.html
{% extends 'base.html' %}
{%block content%}

<h1><span style="color:green">{{media.get_type_display}}:</span> {{media.name}} <span style="color:grey">({{ media.get_status_display }})</span></h1>
<h4>Author: 
    {% for author in media.authors.all %}
        {{author.name}}{% if not forloop.last %}, {% endif %}
    {%endfor%}
</h4>
<h4>Rating: 
    {{media.score}}
</h4>
<h4>Notes:</h4>
<p>{{media.notes}}</p>

{% endblock %}

main_app/templates/media/index.html
{% extends 'base.html' %}
{%block content%}
<h1>Reading List</h1>

<table>
    <thead>
        <tr>
            <th>Name</th>
            <th>Type</th>
            <th>Author</th>
            <th>Rating</th>
            <th>Status</th>
            <th>Notes</th>
        </tr>
    </thead>
    <tbody>
        {% for item in media%}
        
            <tr>
                <td><a href="{%url 'detail' item.id %}">{{ item.name }}</a></td>
                <td>{{ item.get_type_display }}</td>
                <td>{% for author in item.authors.all %}
                        {{author.name}}{% if not forloop.last %}, {% endif %}
                    {%endfor%}</td>
                <td>{{ item.score }}</td>
                <td>
                    {{item.get_status_display}}
                </td>
                <td>{{ item.notes }}</td>
            </tr>
        
        </tbody>
        {% endfor %}
    </tbody>
</table>


{% endblock %}